services:
  tekkenstats:
    container_name: tekkenstats_app
    image: tekkenstats
    build:
      context: .
      dockerfile: TekkenStats.API/Dockerfile
    depends_on:
      - postgres
      - rabbit
  
  postgres:
    container_name: tekkenstats_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tekkenstatsDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  rabbit:
    image: rabbitmq:3-management
    container_name: tekkenstats_q
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

volumes:
  postgres_data:

networks:
  rabbitmq_go_net:
    driver: bridge