services:
  tekkenstats_api:
    container_name: tekkenstats_api
    image: tekkenstats_api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=tekkenstatsDb;User Id=postgres;Password=root;Include Error Detail=true"
      RabbitMQOptions__Host: "rabbit"
      RabbitMQOptions__Username: "guest"
      RabbitMQOptions__Password: "guest"
      MongoOptions__ConnectionString: "mongodb://admin:root@mongo:27017"
      MongoOptions__DbName: "TekkenStats"
    build:
      context: .
      dockerfile: TekkenStats.API/Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - app-network

  tekkenstats_processingService:
    image: tekkenstats_processing_service
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=tekkenstatsDb;User Id=postgres;Password=root;Include Error Detail=true"
      RabbitMQOptions__Host: "rabbit"
      RabbitMQOptions__Username: "guest"
      RabbitMQOptions__Password: "guest"
      MongoOptions__ConnectionString: "mongodb://admin:root@mongo:27017"
      MongoOptions__DbName: "TekkenStats"
    build:
      context: .
      dockerfile: TekkenStats.ProcessingService/Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    container_name: tekkenstats_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tekkenstatsDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  mongo:
    container_name: tekkenstats_mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo_db_data:/data/db

  rabbit:
    image: rabbitmq:3-management
    container_name: tekkenstats_q
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
  mongo_db_data:

networks:
  app-network:
    driver: bridge