services:
  tekkenstats_api:
    container_name: tekkenstats_api
    image: tekkenstats_api
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=tekkenstatsDb;User Id=postgres;Password=root;Include Error Detail=true"
      RabbitMQOptions__Host: "rabbit"
      RabbitMQOptions__Username: "guest"
      RabbitMQOptions__Password: "guest"
      ConnectionStrings__RedisConnection: "redis,password=root"
    build:
      context: .
      dockerfile: TekkenStats.API/Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
    
    networks:
      - app-network

  tekkenstats_processingService:
    image: tekkenstats_processing_service
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=tekkenstatsDb;User Id=postgres;Password=root;Include Error Detail=true"
      RabbitMQOptions__Host: "rabbit"
      RabbitMQOptions__Username: "guest"
      RabbitMQOptions__Password: "guest"
      ConnectionStrings__RedisConnection: "redis,password=root"
    build:
      context: .
      dockerfile: TekkenStats.ProcessingService/Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    container_name: tekkenstats_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tekkenstatsDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbit:
    image: rabbitmq:3-management
    container_name: tekkenstats_q
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  
  redis:
    image: redis:latest
    container_name: tekkenstats_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=root
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge